%% T2 - TANDHJULSKRAFTER, MOMENT, EFFEKT OG VIRKNINGSGRAD
% Brug dette script naar en opgave giver tandhjulenes delecirkeldiametre,
% indgrebsvinkler, hastighed samt moment eller effekt og spoerger efter:
% - moment og effekt paa akslerne
% - tangential-, radial- og aksialkraft i tandhjulene
% - virkningsgrad og effekttab gennem et flertrins gear
%
% Brug ikke dette script til:
% - bestemmelse af tandtal, modul og indgrebsgrad (T1)
% - tandfodsspaending eller tandbredde (T3)
% - leje- eller akselreaktioner uden et manuelt fritlegemediagram
% - keglehjul, snekkegear eller planetgear
%
% Modeller/opslag manuelt foerst:
% 1) Fastlaeg kraftvejen og hvilket hjul der driver i hvert trin.
% 2) Fastlaeg antal lejer, virkningsgrader og tabenes placering.
% 3) Fastlaeg fortegn og retning for Wt, Wr og Wa ud fra rotation,
%    tandhjulsplacering og skråfortandingens haand.
%
% Kursusgrundlag:
% - TANDHJUL_FRL.pdf, side 24-26: T = Wt*d/2 og P = T*omega.
% - TANDHJUL_FRL.pdf, side 35-36: kraefter ved skraafortanding.
% - TANDHJUL_OPGAVE_LOSN.pdf, side 5-6, 8 og 11:
%   flertrinsudveksling, virkningsgrader, momenter og kraefter.
%
% Bemaerkning om kursusloesningen:
% Side 11 angiver Wt3 = T3/(d3/2) = 10.6 kN. Det bruger
% udgangsakslens moment sammen med det drivende pinionhjuls diameter.
% Dette er ikke konsistent med teoriens T = Wt*d/2 og samme Wt paa
% begge hjul. Scriptet bruger derfor momentet paa den drivende aksel
% for hvert indgreb. Afvigelsen rapporteres i regressionstesten.

%% ASSUMPTIONS AND MANUAL INPUT
% - Sekventielle, udvendige tandhjulspar.
% - Det drevne hjul i trin k sidder paa samme aksel som det drivende
%   hjul i trin k+1.
% - Udveksling:
%       i_k = omega_k/omega_(k+1) = dDriven/dDrive
% - Hvert udvendigt indgreb vender rotationsretningen.
% - Kraefter rapporteres som stoerrelser. Retninger skal bestemmes
%   manuelt i et fritlegemediagram.
% - phi_n er normal indgrebsvinkel og psi er skraavinkel.
% - Ved ligefortanding saettes psi = 0 deg, saa Wa = 0.
% - Tab fordeles efter kursusopgavens model:
%       eta_shaft = eta_bearing_per_bearing^numberOfBearings
%   og hvert trin overfoerer:
%       P_(k+1) = P_k * eta_shaft(k) * eta_mesh(k)
%   Udgangsakslens lejetab ligger mellem sidste akselmoment og lasten.
% - Momentet til tandkraften er akselmomentet paa det drivende hjul,
%   saadan som teoriens T = Wt*d/2 foreskriver.
% - Enheder: N, mm, Nm, W, kW, rpm, rad/s og m/s.

%% INPUT
% Et element pr. tandhjulsindgreb.
% Standardeksemplet er den loeste to-trins kursusopgave.
drivePitchDiameterMM = [34, 51];       % [mm] delecirkeldiameter, drivende hjul
drivenPitchDiameterMM = [200, 222];    % [mm] delecirkeldiameter, drevet hjul

normalPressureAngleDeg = [20, 20];     % [deg] normal indgrebsvinkel phi_n
helixAngleDeg = [0, 0];                % [deg] skraavinkel psi; 0 = ligefortanding

meshEfficiency = [0.98, 0.98];         % [-] virkningsgrad pr. tandhjulsindgreb

% Et element pr. aksel. N geartrin giver N+1 aksler.
bearingEfficiencyPerBearing = [0.99, 0.99, 0.99]; % [-] virkningsgrad pr. leje
numberOfBearingsPerShaft = [2, 2, 2];              % [-] antal lejer pr. aksel

% Hastighedsreference. Brug enten input- eller udgangsakslen.
speedReferenceSide = "input";          % "input" eller "output"
speedReferenceUnit = "rpm";            % "rpm" eller "rad_s"
speedReferenceValue = 2930;            % [rpm] eller [rad/s], bestemt af enheden
inputDirection = +1;                   % [-] +1 eller -1

% Kendt moment/effekt. Kursuseksemplet giver udgangslastens moment.
knownQuantitySide = "output";          % "input" eller "output"
knownQuantityType = "torque";          % "torque" eller "power"
knownTorqueNm = 265;                   % [Nm] bruges naar type = "torque"
knownPowerKW = NaN;                    % [kW] bruges naar type = "power"

% Valgfri krav til kontrol. Brug NaN naar kravet ikke er opgivet.
maximumInputPowerKW = 4.0;             % [kW] fx valgt motorstoerrelse
minimumOverallEfficiency = NaN;        % [-] valgfrit virkningsgradskrav

% Plot og regressionstests
makePlots = true;                      % [-] true giver tekniske plots
runCourseRegressionTests = true;       % [-] test mod kursusopgaver

%% UNIT CHECK AND VALIDATION
drivePitchDiameterMM = drivePitchDiameterMM(:).';
drivenPitchDiameterMM = drivenPitchDiameterMM(:).';
normalPressureAngleDeg = normalPressureAngleDeg(:).';
helixAngleDeg = helixAngleDeg(:).';
meshEfficiency = meshEfficiency(:).';
bearingEfficiencyPerBearing = bearingEfficiencyPerBearing(:).';
numberOfBearingsPerShaft = numberOfBearingsPerShaft(:).';

numberOfStages = numel(drivePitchDiameterMM);
numberOfShafts = numberOfStages + 1;

assert(numberOfStages >= 1, ...
    'Der skal vaere mindst ét tandhjulsindgreb.');

assert(numel(drivenPitchDiameterMM) == numberOfStages && ...
       numel(normalPressureAngleDeg) == numberOfStages && ...
       numel(helixAngleDeg) == numberOfStages && ...
       numel(meshEfficiency) == numberOfStages, ...
    ['Diameter-, vinkel- og virkningsgradsvektorer skal have ', ...
     'ét element pr. geartrin.']);

assert(numel(bearingEfficiencyPerBearing) == numberOfShafts && ...
       numel(numberOfBearingsPerShaft) == numberOfShafts, ...
    ['Lejevirkningsgrader og antal lejer skal have ét element ', ...
     'pr. aksel, dvs. N+1 elementer.']);

assert(all(isfinite(drivePitchDiameterMM)) && ...
       all(drivePitchDiameterMM > 0), ...
    'Alle drivende delecirkeldiametre skal vaere positive [mm].');

assert(all(isfinite(drivenPitchDiameterMM)) && ...
       all(drivenPitchDiameterMM > 0), ...
    'Alle drevne delecirkeldiametre skal vaere positive [mm].');

assert(all(isfinite(normalPressureAngleDeg)) && ...
       all(normalPressureAngleDeg > 0 & normalPressureAngleDeg < 90), ...
    'Normal indgrebsvinkel skal ligge mellem 0 og 90 deg.');

assert(all(isfinite(helixAngleDeg)) && ...
       all(abs(helixAngleDeg) < 90), ...
    'Skraavinklens absolutte vaerdi skal vaere under 90 deg.');

assert(all(isfinite(meshEfficiency)) && ...
       all(meshEfficiency > 0 & meshEfficiency <= 1), ...
    'Hver indgrebsvirkningsgrad skal ligge i intervallet ]0,1].');

assert(all(isfinite(bearingEfficiencyPerBearing)) && ...
       all(bearingEfficiencyPerBearing > 0 & ...
           bearingEfficiencyPerBearing <= 1), ...
    'Hver lejevirkningsgrad skal ligge i intervallet ]0,1].');

assert(all(isfinite(numberOfBearingsPerShaft)) && ...
       all(numberOfBearingsPerShaft >= 0) && ...
       all(mod(numberOfBearingsPerShaft,1) == 0), ...
    'Antal lejer pr. aksel skal vaere ikke-negative heltal.');

assert(isscalar(speedReferenceValue) && isfinite(speedReferenceValue) && ...
       speedReferenceValue > 0, ...
    'speedReferenceValue skal vaere positiv.');

assert(any(strcmpi(speedReferenceSide, ["input","output"])), ...
    'speedReferenceSide skal vaere "input" eller "output".');

assert(any(strcmpi(speedReferenceUnit, ["rpm","rad_s"])), ...
    'speedReferenceUnit skal vaere "rpm" eller "rad_s".');

assert(isscalar(inputDirection) && any(inputDirection == [-1,+1]), ...
    'inputDirection skal vaere +1 eller -1.');

assert(any(strcmpi(knownQuantitySide, ["input","output"])), ...
    'knownQuantitySide skal vaere "input" eller "output".');

assert(any(strcmpi(knownQuantityType, ["torque","power"])), ...
    'knownQuantityType skal vaere "torque" eller "power".');

if strcmpi(knownQuantityType, "torque")
    assert(isscalar(knownTorqueNm) && isfinite(knownTorqueNm) && ...
           knownTorqueNm > 0, ...
        'knownTorqueNm skal vaere positiv, naar typen er "torque".');
else
    assert(isscalar(knownPowerKW) && isfinite(knownPowerKW) && ...
           knownPowerKW > 0, ...
        'knownPowerKW skal vaere positiv, naar typen er "power".');
end

assert(isnan(maximumInputPowerKW) || ...
       (isscalar(maximumInputPowerKW) && isfinite(maximumInputPowerKW) && ...
        maximumInputPowerKW > 0), ...
    'maximumInputPowerKW skal vaere positiv eller NaN.');

assert(isnan(minimumOverallEfficiency) || ...
       (isscalar(minimumOverallEfficiency) && ...
        isfinite(minimumOverallEfficiency) && ...
        minimumOverallEfficiency > 0 && minimumOverallEfficiency <= 1), ...
    'minimumOverallEfficiency skal ligge i ]0,1] eller vaere NaN.');

if any(abs(helixAngleDeg) > 0) && ...
        all(abs(normalPressureAngleDeg - 20) < 1e-12)
    warning('T2:CheckPressureAngleConvention', ...
        ['Ved skraafortanding skal du kontrollere, at den opgivne ', ...
         '20-graders vinkel er normalvinklen phi_n.']);
end

%% CALCULATION
calculation = calculateT2GearTrain( ...
    drivePitchDiameterMM, ...
    drivenPitchDiameterMM, ...
    normalPressureAngleDeg, ...
    helixAngleDeg, ...
    meshEfficiency, ...
    bearingEfficiencyPerBearing, ...
    numberOfBearingsPerShaft, ...
    speedReferenceSide, ...
    speedReferenceUnit, ...
    speedReferenceValue, ...
    inputDirection, ...
    knownQuantitySide, ...
    knownQuantityType, ...
    knownTorqueNm, ...
    knownPowerKW);

%% RESULTS
shaftLabel = "Aksel " + string((1:numberOfShafts).');

shaftTable = table( ...
    (1:numberOfShafts).', ...
    shaftLabel, ...
    calculation.shaftSpeedRPM.', ...
    calculation.shaftOmegaRadPerSec.', ...
    calculation.shaftDirection.', ...
    calculation.signedShaftSpeedRPM.', ...
    calculation.shaftPowerW.'/1000, ...
    calculation.shaftTorqueNm.', ...
    calculation.shaftBearingEfficiency.', ...
    calculation.shaftBearingLossW.', ...
    'VariableNames', { ...
    'Shaft', ...
    'Label', ...
    'Speed_rpm', ...
    'Omega_rad_s', ...
    'Direction', ...
    'SignedSpeed_rpm', ...
    'PowerBeforeBearingLoss_kW', ...
    'ShaftTorque_Nm', ...
    'ShaftBearingEfficiency', ...
    'BearingLoss_W'});

stageTable = table( ...
    (1:numberOfStages).', ...
    drivePitchDiameterMM.', ...
    drivenPitchDiameterMM.', ...
    calculation.stageRatio.', ...
    normalPressureAngleDeg.', ...
    helixAngleDeg.', ...
    calculation.transversePressureAngleDeg.', ...
    meshEfficiency.', ...
    calculation.stageCombinedEfficiency.', ...
    calculation.pitchLineVelocityMPerSec.', ...
    calculation.tangentialForceN.', ...
    calculation.radialForceN.', ...
    calculation.axialForceN.', ...
    calculation.fullToothForceN.', ...
    calculation.idealDrivenGearTorqueNm.', ...
    calculation.nextShaftTorqueNm.', ...
    calculation.meshLossW.', ...
    'VariableNames', { ...
    'Stage', ...
    'DrivePitchDiameter_mm', ...
    'DrivenPitchDiameter_mm', ...
    'Ratio', ...
    'NormalPressureAngle_deg', ...
    'HelixAngle_deg', ...
    'TransversePressureAngle_deg', ...
    'MeshEfficiency', ...
    'CombinedStageEfficiency', ...
    'PitchLineVelocity_m_s', ...
    'TangentialForce_N', ...
    'RadialForce_N', ...
    'AxialForce_N', ...
    'FullToothForce_N', ...
    'IdealDrivenGearTorque_Nm', ...
    'NextShaftTorque_Nm', ...
    'MeshLoss_W'});

gearID = strings(2*numberOfStages,1);
gearRole = strings(2*numberOfStages,1);
gearStage = repelem((1:numberOfStages).',2);
gearDiameterMM = reshape( ...
    [drivePitchDiameterMM; drivenPitchDiameterMM], [], 1);
gearTangentialForceN = repelem(calculation.tangentialForceN.',2);
gearRadialForceN = repelem(calculation.radialForceN.',2);
gearAxialForceN = repelem(calculation.axialForceN.',2);
gearFullForceN = repelem(calculation.fullToothForceN.',2);

for k = 1:numberOfStages
    gearID(2*k-1) = "H" + string(2*k-1);
    gearID(2*k) = "H" + string(2*k);
    gearRole(2*k-1) = "Drivende";
    gearRole(2*k) = "Drevet";
end

gearForceTable = table( ...
    gearStage, ...
    gearID, ...
    gearRole, ...
    gearDiameterMM, ...
    gearTangentialForceN, ...
    gearRadialForceN, ...
    gearAxialForceN, ...
    gearFullForceN, ...
    'VariableNames', { ...
    'Stage', ...
    'GearID', ...
    'Role', ...
    'PitchDiameter_mm', ...
    'TangentialForceMagnitude_N', ...
    'RadialForceMagnitude_N', ...
    'AxialForceMagnitude_N', ...
    'FullForceMagnitude_N'});

fprintf('\nT2 - TANDHJULSKRAFTER, MOMENT, EFFEKT OG VIRKNINGSGRAD\n');
fprintf('Definition: i = omega_drivende/omega_drevet = d_drevet/d_drivende\n');
fprintf('Antal geartrin: %d\n', numberOfStages);
fprintf('Samlet udveksling: %.6f\n', calculation.totalRatio);
fprintf('Samlet virkningsgrad inkl. alle angivne lejer: %.4f\n', ...
    calculation.overallEfficiency);
fprintf('Indgang: %.3f rpm, %.3f Nm, %.3f kW\n', ...
    calculation.shaftSpeedRPM(1), ...
    calculation.inputTorqueNm, ...
    calculation.inputPowerW/1000);
fprintf('Udgangslast: %.3f rpm, %.3f Nm, %.3f kW\n\n', ...
    calculation.shaftSpeedRPM(end), ...
    calculation.outputLoadTorqueNm, ...
    calculation.outputLoadPowerW/1000);

disp('Aksler:')
disp(shaftTable)

disp('Geartrin:')
disp(stageTable)

disp('Kraftstoerrelser paa hvert tandhjul:')
disp(gearForceTable)

fprintf(['Kraftfortegn er ikke bestemt automatisk. Brug rotation, ', ...
    'tandhjulsplacering og skraafortandingens haand i FBD.\n']);

results = struct;
results.input = struct( ...
    'drivePitchDiameterMM', drivePitchDiameterMM, ...
    'drivenPitchDiameterMM', drivenPitchDiameterMM, ...
    'normalPressureAngleDeg', normalPressureAngleDeg, ...
    'helixAngleDeg', helixAngleDeg, ...
    'meshEfficiency', meshEfficiency, ...
    'bearingEfficiencyPerBearing', bearingEfficiencyPerBearing, ...
    'numberOfBearingsPerShaft', numberOfBearingsPerShaft);

results.shaftTable = shaftTable;
results.stageTable = stageTable;
results.gearForceTable = gearForceTable;
results.totalRatio = calculation.totalRatio;
results.overallEfficiency = calculation.overallEfficiency;
results.inputTorqueNm = calculation.inputTorqueNm;
results.inputPowerKW = calculation.inputPowerW/1000;
results.outputLoadTorqueNm = calculation.outputLoadTorqueNm;
results.outputLoadPowerKW = calculation.outputLoadPowerW/1000;
results.tangentialForceN = calculation.tangentialForceN;
results.radialForceN = calculation.radialForceN;
results.axialForceN = calculation.axialForceN;
results.fullToothForceN = calculation.fullToothForceN;

%% AUTOMATIC CHECKS
automaticChecksOK = true;

if calculation.maximumPowerConsistencyErrorW <= 1e-8 * ...
        max(1,max(calculation.shaftPowerW))
    fprintf('OK - P = T*omega er opfyldt paa alle aksler.\n');
else
    fprintf('IKKE OK - inkonsistens mellem effekt, moment og hastighed.\n');
    automaticChecksOK = false;
end

if calculation.maximumForcePowerErrorW <= 1e-8 * ...
        max(1,max(calculation.shaftPowerW(1:end-1)))
    fprintf('OK - P = Wt*v er opfyldt for alle drivende tandhjul.\n');
else
    fprintf('IKKE OK - inkonsistens mellem tangentialkraft og effekt.\n');
    automaticChecksOK = false;
end

if calculation.maximumForceReconstructionErrorN <= 1e-8 * ...
        max(1,max(calculation.fullToothForceN))
    fprintf('OK - W er konsistent med Wt, Wr og Wa.\n');
else
    fprintf('IKKE OK - kraftkomponenterne rekonstruerer ikke W.\n');
    automaticChecksOK = false;
end

spurStages = abs(helixAngleDeg) < 1e-12;
if all(abs(calculation.axialForceN(spurStages)) < 1e-10)
    fprintf('OK - ligefortandede trin har Wa = 0.\n');
else
    fprintf('IKKE OK - et ligefortandet trin har ikke Wa = 0.\n');
    automaticChecksOK = false;
end

if ~isnan(maximumInputPowerKW)
    if calculation.inputPowerW/1000 <= maximumInputPowerKW
        fprintf('OK - indgangseffekt %.3f kW <= motorgrænse %.3f kW.\n', ...
            calculation.inputPowerW/1000, maximumInputPowerKW);
    else
        fprintf('IKKE OK - indgangseffekt %.3f kW > motorgrænse %.3f kW.\n', ...
            calculation.inputPowerW/1000, maximumInputPowerKW);
        automaticChecksOK = false;
    end
end

if ~isnan(minimumOverallEfficiency)
    if calculation.overallEfficiency >= minimumOverallEfficiency
        fprintf('OK - samlet virkningsgrad %.4f >= %.4f.\n', ...
            calculation.overallEfficiency, minimumOverallEfficiency);
    else
        fprintf('IKKE OK - samlet virkningsgrad %.4f < %.4f.\n', ...
            calculation.overallEfficiency, minimumOverallEfficiency);
        automaticChecksOK = false;
    end
end

if all(isfinite(calculation.shaftPowerW)) && ...
        all(calculation.shaftPowerW > 0)
    fprintf('OK - alle aksler har positiv, endelig effekt.\n');
else
    fprintf('IKKE OK - mindst én akseleffekt er ikke fysisk mulig.\n');
    automaticChecksOK = false;
end

results.automaticChecksOK = automaticChecksOK;

%% PLOTS
if makePlots
    figure('Name','T2 - effekt gennem gearet');
    plot(1:numberOfShafts, calculation.shaftPowerW/1000, ...
        'o-', 'LineWidth', 1.2, 'MarkerSize', 6);
    grid on
    xlabel('Akselnummer [-]');
    ylabel('Effekt foer akslens lejetab [kW]');
    title('Effektforloeb gennem geartrinnene');
    xticks(1:numberOfShafts);

    figure('Name','T2 - tandhjulskraefter');
    forceMatrixKN = [ ...
        calculation.tangentialForceN(:), ...
        calculation.radialForceN(:), ...
        calculation.axialForceN(:)] / 1000;
    bar(1:numberOfStages, forceMatrixKN);
    grid on
    xlabel('Geartrin [-]');
    ylabel('Kraftstoerrelse [kN]');
    title('Tandkraftens komponenter pr. geartrin');
    legend('W_t','W_r','W_a','Location','best');
    xticks(1:numberOfStages);
end

%% PHYSICAL CONCLUSION
fprintf('\nFYSISK KONKLUSION:\n');
fprintf(['Gearet reducerer hastigheden med i_total = %.3f og har en ', ...
    'samlet virkningsgrad paa %.3f.\n'], ...
    calculation.totalRatio, calculation.overallEfficiency);

[maximumForceN, criticalStage] = max(calculation.fullToothForceN);
fprintf(['Stoerste fulde tandkraft er %.3f kN i trin %d. Dette trin ', ...
    'vil typisk vaere vigtigt for aksel- og lejedimensionering.\n'], ...
    maximumForceN/1000, criticalStage);

if any(abs(helixAngleDeg) > 0)
    fprintf(['Mindst ét trin er skraafortandet og giver aksialkraft. ', ...
        'Aksialretningen skal fastlaegges manuelt.\n']);
else
    fprintf('Alle trin er ligefortandede, saa den aksiale tandkraft er nul.\n');
end

fprintf(['Resultatet er ikke et komplet FBD: globale x-, y- og z-retninger ', ...
    'afhaenger stadig af tandhjulenes placering og rotationsretning.\n']);

%% OPTIONAL TEST CASES
if runCourseRegressionTests
    testName = strings(4,1);
    testPassed = false(4,1);
    testDetail = strings(4,1);

    % Test 1: To-trins kursusopgave.
    courseCase = calculateT2GearTrain( ...
        [34,51], [200,222], [20,20], [0,0], ...
        [0.98,0.98], [0.99,0.99,0.99], [2,2,2], ...
        "input", "rpm", 2930, +1, ...
        "output", "torque", 265, NaN);

    testName(1) = "Kursus: motor og foerste indgreb";
    testPassed(1) = ...
        abs(courseCase.inputTorqueNm - 11.4458665482) < 1e-8 && ...
        abs(courseCase.inputPowerW/1000 - 3.5119224422) < 1e-8 && ...
        abs(courseCase.tangentialForceN(1) - 673.286267538) < 1e-6 && ...
        abs(courseCase.radialForceN(1) - 245.056160520) < 1e-6;
    testDetail(1) = sprintf([ ...
        'Tin=%.3f Nm, Pin=%.3f kW, Wt1=%.0f N, Wr1=%.0f N'], ...
        courseCase.inputTorqueNm, ...
        courseCase.inputPowerW/1000, ...
        courseCase.tangentialForceN(1), ...
        courseCase.radialForceN(1));

    % Test 2: Teorikonsistent kraft i andet indgreb.
    testName(2) = "Kursus: kontrol af andet indgreb";
    courseReportedSecondStageForceN = 10600;
    discrepancyPercent = abs( ...
        courseReportedSecondStageForceN - ...
        courseCase.tangentialForceN(2)) / ...
        courseCase.tangentialForceN(2) * 100;

    testPassed(2) = ...
        abs(courseCase.tangentialForceN(2) - 2536.03966030) < 1e-6 && ...
        abs(courseCase.radialForceN(2) - 923.042949300) < 1e-6 && ...
        discrepancyPercent > 300;

    testDetail(2) = sprintf([ ...
        'Teori: Wt2=%.3f kN; kursusside 11: 10.6 kN; ', ...
        'afvigelse=%.1f %%'], ...
        courseCase.tangentialForceN(2)/1000, ...
        discrepancyPercent);

    % Test 3: Simpelt, haandkontrollerbart ligefortandet gear uden tab.
    simpleSpurCase = calculateT2GearTrain( ...
        100, 200, 20, 0, 1, [1,1], [0,0], ...
        "input", "rpm", 1000, +1, ...
        "input", "torque", 100, NaN);

    expectedPowerW = 100 * (1000*2*pi/60);
    expectedRadialForceN = 2000*tand(20);

    testName(3) = "Haandcheck: ét ligefortandet trin";
    testPassed(3) = ...
        abs(simpleSpurCase.tangentialForceN - 2000) < 1e-10 && ...
        abs(simpleSpurCase.radialForceN - expectedRadialForceN) < 1e-10 && ...
        abs(simpleSpurCase.axialForceN) < 1e-10 && ...
        abs(simpleSpurCase.outputLoadTorqueNm - 200) < 1e-10 && ...
        abs(simpleSpurCase.inputPowerW - expectedPowerW) < 1e-8;

    testDetail(3) = sprintf([ ...
        'Wt=%.1f N, Wr=%.1f N, Tout=%.1f Nm'], ...
        simpleSpurCase.tangentialForceN, ...
        simpleSpurCase.radialForceN, ...
        simpleSpurCase.outputLoadTorqueNm);

    % Test 4: Skraafortanding fra kursusformlerne 13-19, 13-39 og 13-40.
    simpleHelicalCase = calculateT2GearTrain( ...
        100, 200, 20, 15, 1, [1,1], [0,0], ...
        "input", "rpm", 1000, +1, ...
        "input", "torque", 100, NaN);

    expectedTransverseAngleDeg = ...
        atand(tand(20)/cosd(15));
    expectedHelicalRadialN = ...
        2000*tand(expectedTransverseAngleDeg);
    expectedHelicalAxialN = ...
        2000*tand(15);
    expectedFullForceN = ...
        2000/(cosd(20)*cosd(15));

    testName(4) = "Haandcheck: skraafortandet trin";
    testPassed(4) = ...
        abs(simpleHelicalCase.transversePressureAngleDeg - ...
            expectedTransverseAngleDeg) < 1e-10 && ...
        abs(simpleHelicalCase.radialForceN - ...
            expectedHelicalRadialN) < 1e-10 && ...
        abs(simpleHelicalCase.axialForceN - ...
            expectedHelicalAxialN) < 1e-10 && ...
        abs(simpleHelicalCase.fullToothForceN - ...
            expectedFullForceN) < 1e-10;

    testDetail(4) = sprintf([ ...
        'phi_t=%.3f deg, Wr=%.1f N, Wa=%.1f N, W=%.1f N'], ...
        simpleHelicalCase.transversePressureAngleDeg, ...
        simpleHelicalCase.radialForceN, ...
        simpleHelicalCase.axialForceN, ...
        simpleHelicalCase.fullToothForceN);

    testTable = table(testName, testPassed, testDetail, ...
        'VariableNames', {'Test','Passed','Detail'});

    disp('Indbyggede regressionstests:')
    disp(testTable)

    results.courseTests = testTable;

    if all(testPassed)
        fprintf('OK - alle fire indbyggede tests bestod.\n');
    else
        error('T2:RegressionTestFailed', ...
            'Mindst én indbygget regressionstest fejlede.');
    end
end

%% LOCAL FUNCTIONS
function out = calculateT2GearTrain( ...
    drivePitchDiameterMM, ...
    drivenPitchDiameterMM, ...
    normalPressureAngleDeg, ...
    helixAngleDeg, ...
    meshEfficiency, ...
    bearingEfficiencyPerBearing, ...
    numberOfBearingsPerShaft, ...
    speedReferenceSide, ...
    speedReferenceUnit, ...
    speedReferenceValue, ...
    inputDirection, ...
    knownQuantitySide, ...
    knownQuantityType, ...
    knownTorqueNm, ...
    knownPowerKW)

    drivePitchDiameterMM = drivePitchDiameterMM(:).';
    drivenPitchDiameterMM = drivenPitchDiameterMM(:).';
    normalPressureAngleDeg = normalPressureAngleDeg(:).';
    helixAngleDeg = helixAngleDeg(:).';
    meshEfficiency = meshEfficiency(:).';
    bearingEfficiencyPerBearing = bearingEfficiencyPerBearing(:).';
    numberOfBearingsPerShaft = numberOfBearingsPerShaft(:).';

    numberOfStages = numel(drivePitchDiameterMM);
    numberOfShafts = numberOfStages + 1;

    stageRatio = drivenPitchDiameterMM ./ drivePitchDiameterMM;
    totalRatio = prod(stageRatio);

    shaftBearingEfficiency = ...
        bearingEfficiencyPerBearing .^ numberOfBearingsPerShaft;

    shaftSpeedRPM = zeros(1,numberOfShafts);

    if strcmpi(speedReferenceUnit,"rpm")
        referenceSpeedRPM = speedReferenceValue;
    else
        referenceSpeedRPM = speedReferenceValue * 60/(2*pi);
    end

    if strcmpi(speedReferenceSide,"input")
        shaftSpeedRPM(1) = referenceSpeedRPM;

        for k = 1:numberOfStages
            shaftSpeedRPM(k+1) = shaftSpeedRPM(k)/stageRatio(k);
        end
    else
        shaftSpeedRPM(end) = referenceSpeedRPM;

        for k = numberOfStages:-1:1
            shaftSpeedRPM(k) = shaftSpeedRPM(k+1)*stageRatio(k);
        end
    end

    shaftOmegaRadPerSec = shaftSpeedRPM*2*pi/60;

    shaftDirection = zeros(1,numberOfShafts);
    shaftDirection(1) = inputDirection;

    for k = 1:numberOfStages
        shaftDirection(k+1) = -shaftDirection(k);
    end

    signedShaftSpeedRPM = shaftDirection .* shaftSpeedRPM;

    shaftPowerW = zeros(1,numberOfShafts);

    if strcmpi(knownQuantitySide,"input")
        if strcmpi(knownQuantityType,"torque")
            shaftPowerW(1) = knownTorqueNm*shaftOmegaRadPerSec(1);
        else
            shaftPowerW(1) = knownPowerKW*1000;
        end

        for k = 1:numberOfStages
            shaftPowerW(k+1) = shaftPowerW(k) * ...
                shaftBearingEfficiency(k) * meshEfficiency(k);
        end

        outputLoadPowerW = ...
            shaftPowerW(end)*shaftBearingEfficiency(end);
    else
        if strcmpi(knownQuantityType,"torque")
            outputLoadPowerW = ...
                knownTorqueNm*shaftOmegaRadPerSec(end);
        else
            outputLoadPowerW = knownPowerKW*1000;
        end

        shaftPowerW(end) = ...
            outputLoadPowerW/shaftBearingEfficiency(end);

        for k = numberOfStages:-1:1
            shaftPowerW(k) = shaftPowerW(k+1) / ...
                (shaftBearingEfficiency(k)*meshEfficiency(k));
        end
    end

    shaftTorqueNm = shaftPowerW ./ shaftOmegaRadPerSec;

    inputPowerW = shaftPowerW(1);
    inputTorqueNm = shaftTorqueNm(1);
    outputLoadTorqueNm = ...
        outputLoadPowerW/shaftOmegaRadPerSec(end);

    stageCombinedEfficiency = ...
        shaftBearingEfficiency(1:end-1).*meshEfficiency;

    overallEfficiency = ...
        prod(stageCombinedEfficiency)*shaftBearingEfficiency(end);

    transversePressureAngleDeg = atand( ...
        tand(normalPressureAngleDeg)./cosd(helixAngleDeg));

    pitchLineVelocityMPerSec = ...
        (drivePitchDiameterMM/2000) .* ...
        shaftOmegaRadPerSec(1:end-1);

    tangentialForceN = ...
        2*shaftTorqueNm(1:end-1)*1000 ./ drivePitchDiameterMM;

    radialForceN = ...
        tangentialForceN .* tand(transversePressureAngleDeg);

    axialForceN = ...
        tangentialForceN .* abs(tand(helixAngleDeg));

    fullToothForceN = ...
        tangentialForceN ./ ...
        (cosd(normalPressureAngleDeg).*cosd(helixAngleDeg));

    idealDrivenGearTorqueNm = ...
        tangentialForceN .* drivenPitchDiameterMM / 2000;

    nextShaftTorqueNm = shaftTorqueNm(2:end);

    shaftBearingLossW = ...
        shaftPowerW .* (1-shaftBearingEfficiency);

    powerEnteringMeshW = ...
        shaftPowerW(1:end-1).*shaftBearingEfficiency(1:end-1);

    meshLossW = ...
        powerEnteringMeshW.*(1-meshEfficiency);

    maximumPowerConsistencyErrorW = max(abs( ...
        shaftPowerW - shaftTorqueNm.*shaftOmegaRadPerSec));

    forcePowerW = ...
        tangentialForceN.*pitchLineVelocityMPerSec;

    maximumForcePowerErrorW = max(abs( ...
        forcePowerW - shaftPowerW(1:end-1)));

    reconstructedForceN = sqrt( ...
        tangentialForceN.^2 + ...
        radialForceN.^2 + ...
        axialForceN.^2);

    maximumForceReconstructionErrorN = max(abs( ...
        reconstructedForceN - fullToothForceN));

    out = struct;
    out.stageRatio = stageRatio;
    out.totalRatio = totalRatio;
    out.shaftBearingEfficiency = shaftBearingEfficiency;
    out.stageCombinedEfficiency = stageCombinedEfficiency;
    out.overallEfficiency = overallEfficiency;
    out.shaftSpeedRPM = shaftSpeedRPM;
    out.shaftOmegaRadPerSec = shaftOmegaRadPerSec;
    out.shaftDirection = shaftDirection;
    out.signedShaftSpeedRPM = signedShaftSpeedRPM;
    out.shaftPowerW = shaftPowerW;
    out.shaftTorqueNm = shaftTorqueNm;
    out.inputPowerW = inputPowerW;
    out.inputTorqueNm = inputTorqueNm;
    out.outputLoadPowerW = outputLoadPowerW;
    out.outputLoadTorqueNm = outputLoadTorqueNm;
    out.transversePressureAngleDeg = transversePressureAngleDeg;
    out.pitchLineVelocityMPerSec = pitchLineVelocityMPerSec;
    out.tangentialForceN = tangentialForceN;
    out.radialForceN = radialForceN;
    out.axialForceN = axialForceN;
    out.fullToothForceN = fullToothForceN;
    out.idealDrivenGearTorqueNm = idealDrivenGearTorqueNm;
    out.nextShaftTorqueNm = nextShaftTorqueNm;
    out.shaftBearingLossW = shaftBearingLossW;
    out.meshLossW = meshLossW;
    out.maximumPowerConsistencyErrorW = ...
        maximumPowerConsistencyErrorW;
    out.maximumForcePowerErrorW = ...
        maximumForcePowerErrorW;
    out.maximumForceReconstructionErrorN = ...
        maximumForceReconstructionErrorN;
end
