%% T3 - TANDFODSSPAENDING OG NOEDVENDIG TANDBREDDE
% Rettelse 2026-06-18: robuste tabeldimensioner for baade ét og flere trin.
% Brug dette script naar en opgave omhandler et eller flere standard,
% ligefortandede, udvendige evolvent-tandhjulspar og spoerger efter:
% - boejningsspaending i tandfoden
% - noedvendig faelles tandbredde for et tandhjulspar
% - hvilket hjul der er kritisk
%
% Brug ikke dette script til:
% - skraafortanding, profilforskydning eller indvendige tandhjul
% - tandflanketryk/pitting
% - fuld AGMA/ISO-beregning med faktorer, som ikke indgaar i kursets
%   reducerede metode
% - bestemmelse af tandkraft uden at moment eller Wt er kendt
%
% Kursusmetode:
%   sigma = Kv*Wt/(b*m*Y)
%   Y     = 1/(Ke*KF)
%   Ke    = 1/mc
%   KF    = 2.2 + 3.1*exp(-N/14)
%
% Den dynamiske faktor beregnes som:
%   Kv = ((A + sqrt(200*V))/A)^B
%   A  = 50 + 56*(1-B)
%   B  = 0.25*(12-Qv)^(2/3)
%
% Modeller/opslag manuelt foerst:
% 1) Fastlaeg den tangentiale tandkraft Wt eller det drivende moment.
% 2) Fastlaeg hastigheden paa det drivende hjul eller periferihastigheden.
% 3) Angiv den tilladelige tandfodsspaending for hvert materiale.
% 4) Angiv eventuelle tilgaengelige standardbredder. Scriptet opfinder
%    ikke standardmaal.
%
% Kursusgrundlag:
% - Eksempeleksamen, problem 1 og formelsamlingen.
% - TANDHJUL_FRL.pdf, afsnittet om tandfodsbrud og dynamisk faktor.
% - TANDHJUL_OPGAVE_LOSN.pdf, styrkeundersoegelse af tandhjul.

clear; clc; close all;

%% ASSUMPTIONS AND MANUAL INPUT
% - Standard, ligefortandede, udvendige tandhjul uden profilforskydning.
% - Samme modul, indgrebsvinkel og tandbredde for hjulene i hvert par.
% - Wt er den samme kraftstoerrelse paa begge hjul i et indgreb.
% - Kursusformlen anvendes i N, mm og MPa:
%       1 MPa = 1 N/mm^2
% - Kv er faelles for de to hjul i samme indgreb.
% - Indgrebsgraden kan beregnes fra standardgeometrien eller indtastes
%   manuelt fra T1.
% - Kraft-, moment- og hastighedsinput skal hoere til det drivende hjul.
% - Spaendingen er en dynamisk, nominel tandfodsspaending efter den
%   reducerede kursusmetode. Lokale effekter uden for metoden er ikke
%   automatisk inkluderet.

%% INPUT
% Et element pr. tandhjulsindgreb.
% Standardinputtet er eksempeleksamen, problem 1.
zDrive = 18;                       % [-] tandtal, drivende hjul
zDriven = 45;                      % [-] tandtal, drevet hjul
moduleStageMM = 4;                 % [mm] modul
pressureAngleDeg = 20;             % [deg] indgrebsvinkel
qualityNumberQv = 3;               % [-] kvalitetstal, kursusinterval 3...12

% Belastning: vaelg "torque" eller "force".
loadInputMode = "torque";          % [-] "torque" eller "force"
driveTorqueNm = 220;                % [Nm] moment paa drivende hjul
tangentialForceN = NaN;            % [N] Wt, bruges ved "force"

% Hastighed: vaelg "rpm" eller "velocity".
speedInputMode = "rpm";            % [-] "rpm" eller "velocity"
driveSpeedRPM = 1800;              % [rpm] drivende hjuls omdrejningstal
pitchLineVelocityMPerSec = NaN;    % [m/s] bruges ved "velocity"

% Indgrebsgrad: vaelg "calculate" eller "manual".
contactRatioMode = "calculate";    % [-] "calculate" eller "manual"
manualContactRatio = NaN;          % [-] mc fra T1, bruges ved "manual"
minimumContactRatio = 1.20;        % [-] kursuskrav til indgrebsgrad

% Materialekrav. Et element pr. drivende/drevet hjul.
allowableStressDriveMPa = 200;     % [MPa] tilladt tandfodsspaending, drivende
allowableStressDrivenMPa = 200;    % [MPa] tilladt tandfodsspaending, drevet

% Kendt tandbredde. Brug NaN for ren dimensionering.
faceWidthStageMM = NaN;            % [mm] faelles tandbredde i hvert indgreb

% Valgfri liste med faktisk tilgaengelige standardbredder [mm].
% Tom vektor betyder, at ingen standardserie er leveret.
availableStandardFaceWidthsMM = []; % [mm] fx [20 25 30 35], kun hvis opgivet

% Plot og indbyggede test
makeWidthSweepPlot = true;         % [-] true giver bredde-spaendingsplot
runCourseRegressionTests = true;   % [-] test mod kursusopgaver

%% UNIT CHECK AND VALIDATION
zDrive = zDrive(:).';
zDriven = zDriven(:).';
moduleStageMM = moduleStageMM(:).';
pressureAngleDeg = pressureAngleDeg(:).';
qualityNumberQv = qualityNumberQv(:).';
driveTorqueNm = driveTorqueNm(:).';
tangentialForceN = tangentialForceN(:).';
driveSpeedRPM = driveSpeedRPM(:).';
pitchLineVelocityMPerSec = pitchLineVelocityMPerSec(:).';
manualContactRatio = manualContactRatio(:).';
allowableStressDriveMPa = allowableStressDriveMPa(:).';
allowableStressDrivenMPa = allowableStressDrivenMPa(:).';
faceWidthStageMM = faceWidthStageMM(:).';
availableStandardFaceWidthsMM = ...
    sort(unique(availableStandardFaceWidthsMM(:).'));

numberOfStages = numel(zDrive);

assert(numberOfStages >= 1, ...
    'Der skal vaere mindst ét tandhjulsindgreb.');

assert(numel(zDriven) == numberOfStages && ...
       numel(moduleStageMM) == numberOfStages && ...
       numel(pressureAngleDeg) == numberOfStages && ...
       numel(qualityNumberQv) == numberOfStages, ...
    ['zDrive, zDriven, moduleStageMM, pressureAngleDeg og ', ...
     'qualityNumberQv skal have samme laengde.']);

assert(numel(driveTorqueNm) == numberOfStages && ...
       numel(tangentialForceN) == numberOfStages && ...
       numel(driveSpeedRPM) == numberOfStages && ...
       numel(pitchLineVelocityMPerSec) == numberOfStages && ...
       numel(manualContactRatio) == numberOfStages && ...
       numel(allowableStressDriveMPa) == numberOfStages && ...
       numel(allowableStressDrivenMPa) == numberOfStages && ...
       numel(faceWidthStageMM) == numberOfStages, ...
    'Alle trinvise input skal have ét element pr. indgreb.');

assert(all(isfinite(zDrive)) && all(isfinite(zDriven)) && ...
       all(zDrive > 0) && all(zDriven > 0) && ...
       all(mod(zDrive,1) == 0) && all(mod(zDriven,1) == 0), ...
    'Tandtallene skal vaere positive heltal.');

assert(all(isfinite(moduleStageMM)) && all(moduleStageMM > 0), ...
    'Modulerne skal vaere positive [mm].');

assert(all(isfinite(pressureAngleDeg)) && ...
       all(pressureAngleDeg > 0 & pressureAngleDeg < 90), ...
    'Indgrebsvinklerne skal ligge mellem 0 og 90 deg.');

assert(all(isfinite(qualityNumberQv)) && ...
       all(qualityNumberQv >= 3 & qualityNumberQv <= 12), ...
    'Kursusformlen for Kv anvendes for Qv i intervallet 3...12.');

assert(any(strcmpi(loadInputMode, ["torque","force"])), ...
    'loadInputMode skal vaere "torque" eller "force".');

assert(any(strcmpi(speedInputMode, ["rpm","velocity"])), ...
    'speedInputMode skal vaere "rpm" eller "velocity".');

assert(any(strcmpi(contactRatioMode, ["calculate","manual"])), ...
    'contactRatioMode skal vaere "calculate" eller "manual".');

if strcmpi(loadInputMode, "torque")
    assert(all(isfinite(driveTorqueNm)) && all(driveTorqueNm > 0), ...
        'driveTorqueNm skal vaere positiv for alle trin.');
else
    assert(all(isfinite(tangentialForceN)) && ...
           all(tangentialForceN > 0), ...
        'tangentialForceN skal vaere positiv for alle trin.');
end

if strcmpi(speedInputMode, "rpm")
    assert(all(isfinite(driveSpeedRPM)) && all(driveSpeedRPM > 0), ...
        'driveSpeedRPM skal vaere positiv for alle trin.');
else
    assert(all(isfinite(pitchLineVelocityMPerSec)) && ...
           all(pitchLineVelocityMPerSec >= 0), ...
        'pitchLineVelocityMPerSec skal vaere ikke-negativ.');
end

if strcmpi(contactRatioMode, "manual")
    assert(all(isfinite(manualContactRatio)) && ...
           all(manualContactRatio > 0), ...
        'manualContactRatio skal vaere positiv for alle trin.');
end

assert(all(isfinite(allowableStressDriveMPa)) && ...
       all(allowableStressDriveMPa > 0) && ...
       all(isfinite(allowableStressDrivenMPa)) && ...
       all(allowableStressDrivenMPa > 0), ...
    'Tilladelige spaendinger skal vaere positive [MPa].');

assert(all(isnan(faceWidthStageMM) | ...
       (isfinite(faceWidthStageMM) & faceWidthStageMM > 0)), ...
    'faceWidthStageMM skal vaere positiv [mm] eller NaN.');

assert(isfinite(minimumContactRatio) && minimumContactRatio > 0, ...
    'minimumContactRatio skal vaere positiv.');

assert(all(isfinite(availableStandardFaceWidthsMM)) && ...
       all(availableStandardFaceWidthsMM > 0), ...
    'Standardbredder skal vaere positive [mm].');

if any(abs(pressureAngleDeg - 20) > 1e-12)
    warning('T3:PressureAngle', ...
        ['Kursets normale standardeksempler bruger 20 deg. ', ...
         'Kontrollér den opgivne vinkel.']);
end

%% CALCULATION
calculation = calculateT3SpurGear( ...
    zDrive, ...
    zDriven, ...
    moduleStageMM, ...
    pressureAngleDeg, ...
    qualityNumberQv, ...
    loadInputMode, ...
    driveTorqueNm, ...
    tangentialForceN, ...
    speedInputMode, ...
    driveSpeedRPM, ...
    pitchLineVelocityMPerSec, ...
    contactRatioMode, ...
    manualContactRatio, ...
    allowableStressDriveMPa, ...
    allowableStressDrivenMPa, ...
    faceWidthStageMM, ...
    availableStandardFaceWidthsMM, ...
    minimumContactRatio);

%% RESULTS
stageNumber = (1:numberOfStages).';

stageTable = table( ...
    stageNumber, ...
    calculation.drivePitchDiameterMM.', ...
    calculation.drivenPitchDiameterMM.', ...
    calculation.stageRatio.', ...
    calculation.contactRatioCalculated.', ...
    calculation.contactRatioUsed.', ...
    calculation.contactRatioSource(:), ...
    calculation.pitchLineVelocityMPerSec.', ...
    qualityNumberQv.', ...
    calculation.dynamicParameterA.', ...
    calculation.dynamicParameterB.', ...
    calculation.dynamicFactorKv.', ...
    calculation.tangentialForceN.', ...
    calculation.requiredStageWidthMM.', ...
    faceWidthStageMM.', ...
    calculation.selectedStandardWidthMM.', ...
    calculation.criticalRole(:), ...
    calculation.stageStatus(:), ...
    'VariableNames', { ...
    'Stage', ...
    'DrivePitchDiameter_mm', ...
    'DrivenPitchDiameter_mm', ...
    'Ratio', ...
    'ContactRatioCalculated', ...
    'ContactRatioUsed', ...
    'ContactRatioSource', ...
    'PitchLineVelocity_m_s', ...
    'QualityNumber_Qv', ...
    'DynamicParameter_A', ...
    'DynamicParameter_B', ...
    'DynamicFactor_Kv', ...
    'TangentialForce_N', ...
    'RequiredStageWidth_mm', ...
    'ActualFaceWidth_mm', ...
    'SelectedStandardWidth_mm', ...
    'CriticalGear', ...
    'Status'});

gearStage = repelem(stageNumber(:),2,1);
gearID = strings(2*numberOfStages,1);
gearRole = strings(2*numberOfStages,1);

for k = 1:numberOfStages
    gearID(2*k-1) = "H" + string(2*k-1);
    gearID(2*k) = "H" + string(2*k);
    gearRole(2*k-1) = "Drivende";
    gearRole(2*k) = "Drevet";
end

gearTeeth = reshape([zDrive;zDriven],[],1);
gearModuleMM = repelem(moduleStageMM(:),2,1);
gearPitchDiameterMM = reshape([ ...
    calculation.drivePitchDiameterMM; ...
    calculation.drivenPitchDiameterMM],[],1);
gearFormFactorKF = reshape([ ...
    calculation.formFactorDrive; ...
    calculation.formFactorDriven],[],1);
gearContactFactorKe = repelem(calculation.contactFactorKe(:),2,1);
gearLewisFactorY = reshape([ ...
    calculation.lewisFactorDrive; ...
    calculation.lewisFactorDriven],[],1);
gearDynamicFactorKv = repelem(calculation.dynamicFactorKv(:),2,1);
gearTangentialForceN = repelem(calculation.tangentialForceN(:),2,1);
gearRequiredWidthMM = reshape([ ...
    calculation.requiredWidthDriveMM; ...
    calculation.requiredWidthDrivenMM],[],1);
gearActualWidthMM = repelem(faceWidthStageMM(:),2,1);
gearStressMPa = reshape([ ...
    calculation.stressDriveMPa; ...
    calculation.stressDrivenMPa],[],1);
gearAllowableStressMPa = reshape([ ...
    allowableStressDriveMPa; ...
    allowableStressDrivenMPa],[],1);
gearSafetyFactor = reshape([ ...
    calculation.safetyFactorDrive; ...
    calculation.safetyFactorDriven],[],1);
gearStatus = reshape([ ...
    calculation.gearStatusDrive; ...
    calculation.gearStatusDriven],[],1);

% Robust dimensionskontrol: alle gearkolonner skal vaere 2*N x 1.
gearTableColumns = { ...
    gearStage,gearID,gearRole,gearTeeth,gearModuleMM, ...
    gearPitchDiameterMM,gearFormFactorKF,gearContactFactorKe, ...
    gearLewisFactorY,gearDynamicFactorKv,gearTangentialForceN, ...
    gearRequiredWidthMM,gearActualWidthMM,gearStressMPa, ...
    gearAllowableStressMPa,gearSafetyFactor,gearStatus};

gearColumnIsValid = cellfun( ...
    @(x) iscolumn(x) && numel(x) == 2*numberOfStages, ...
    gearTableColumns);

assert(all(gearColumnIsValid), ...
    ['Intern tabelfejl: alle gearTable-kolonner skal vaere ', ...
     'soejlevektorer med 2*numberOfStages elementer.']);

gearTable = table( ...
    gearStage, ...
    gearID, ...
    gearRole, ...
    gearTeeth, ...
    gearModuleMM, ...
    gearPitchDiameterMM, ...
    gearFormFactorKF, ...
    gearContactFactorKe, ...
    gearLewisFactorY, ...
    gearDynamicFactorKv, ...
    gearTangentialForceN, ...
    gearRequiredWidthMM, ...
    gearActualWidthMM, ...
    gearStressMPa, ...
    gearAllowableStressMPa, ...
    gearSafetyFactor, ...
    gearStatus, ...
    'VariableNames', { ...
    'Stage', ...
    'GearID', ...
    'Role', ...
    'Teeth', ...
    'Module_mm', ...
    'PitchDiameter_mm', ...
    'FormFactor_KF', ...
    'ContactFactor_Ke', ...
    'LewisFactor_Y', ...
    'DynamicFactor_Kv', ...
    'TangentialForce_N', ...
    'RequiredWidth_mm', ...
    'ActualWidth_mm', ...
    'ToothRootStress_MPa', ...
    'AllowableStress_MPa', ...
    'SafetyFactor', ...
    'Status'});

fprintf('\nT3 - TANDFODSSPAENDING OG NOEDVENDIG TANDBREDDE\n');
fprintf(['Kursusformel: sigma = Kv*Wt/(b*m*Y), ', ...
    'Y = 1/(Ke*KF), Ke = 1/mc\n']);
fprintf('Antal tandhjulsindgreb: %d\n\n',numberOfStages);

disp('Resultater pr. indgreb:')
disp(stageTable)

disp('Resultater pr. tandhjul:')
disp(gearTable)

for k = 1:numberOfStages
    fprintf(['Trin %d: Kontinuerligt breddekrav = %.3f mm, ', ...
        'kritisk hjul = %s.\n'], ...
        k, ...
        calculation.requiredStageWidthMM(k), ...
        char(calculation.criticalRole(k)));

    if ~isnan(calculation.selectedStandardWidthMM(k))
        fprintf('         Valgt leveret standardbredde = %.3f mm.\n', ...
            calculation.selectedStandardWidthMM(k));
    end
end

results = struct;
results.input = struct( ...
    'zDrive',zDrive, ...
    'zDriven',zDriven, ...
    'moduleStageMM',moduleStageMM, ...
    'pressureAngleDeg',pressureAngleDeg, ...
    'qualityNumberQv',qualityNumberQv, ...
    'loadInputMode',loadInputMode, ...
    'speedInputMode',speedInputMode, ...
    'contactRatioMode',contactRatioMode);

results.stageTable = stageTable;
results.gearTable = gearTable;
results.contactRatioCalculated = calculation.contactRatioCalculated;
results.contactRatioUsed = calculation.contactRatioUsed;
results.dynamicFactorKv = calculation.dynamicFactorKv;
results.tangentialForceN = calculation.tangentialForceN;
results.requiredStageWidthMM = calculation.requiredStageWidthMM;
results.selectedStandardWidthMM = calculation.selectedStandardWidthMM;
results.stressDriveMPa = calculation.stressDriveMPa;
results.stressDrivenMPa = calculation.stressDrivenMPa;
results.allProvidedWidthsOK = calculation.allProvidedWidthsOK;

%% AUTOMATIC CHECKS
allChecksOK = true;

for k = 1:numberOfStages
    if calculation.contactRatioUsed(k) >= minimumContactRatio
        fprintf('OK - trin %d: indgrebsgrad %.3f >= %.2f.\n', ...
            k,calculation.contactRatioUsed(k),minimumContactRatio);
    else
        fprintf('IKKE OK - trin %d: indgrebsgrad %.3f < %.2f.\n', ...
            k,calculation.contactRatioUsed(k),minimumContactRatio);
        allChecksOK = false;
    end

    if strcmpi(contactRatioMode,"manual")
        relativeContactDifference = abs( ...
            calculation.contactRatioUsed(k) - ...
            calculation.contactRatioCalculated(k)) / ...
            calculation.contactRatioCalculated(k);

        if relativeContactDifference > 0.01
            fprintf(['ADVARSEL - trin %d: manuelt mc afviger %.2f %% ', ...
                'fra standardgeometrien. Det kan vaere korrekt ved ', ...
                'anden geometri, men skal begrundes.\n'], ...
                k,100*relativeContactDifference);
        end
    end

    if isnan(faceWidthStageMM(k))
        fprintf(['ADVARSEL - trin %d: ingen faktisk tandbredde er ', ...
            'angivet; kun breddekravet er beregnet.\n'],k);
    elseif calculation.stageWidthOK(k)
        fprintf(['OK - trin %d: b = %.3f mm >= b_kraevet = ', ...
            '%.3f mm.\n'], ...
            k,faceWidthStageMM(k), ...
            calculation.requiredStageWidthMM(k));
    else
        fprintf(['IKKE OK - trin %d: b = %.3f mm < b_kraevet = ', ...
            '%.3f mm.\n'], ...
            k,faceWidthStageMM(k), ...
            calculation.requiredStageWidthMM(k));
        allChecksOK = false;
    end

    if ~isempty(availableStandardFaceWidthsMM) && ...
            isnan(calculation.selectedStandardWidthMM(k))
        fprintf(['ADVARSEL - trin %d: ingen leveret standardbredde ', ...
            'opfylder det kontinuerlige breddekrav.\n'],k);
    end
end

forceReconstructionErrorN = max(abs( ...
    calculation.tangentialForceN - ...
    2*calculation.equivalentDriveTorqueNm*1000 ./ ...
    calculation.drivePitchDiameterMM));

if forceReconstructionErrorN <= ...
        1e-10*max(1,max(calculation.tangentialForceN))
    fprintf('OK - Wt = 2*T/d er enhedskonsistent.\n');
else
    fprintf('IKKE OK - inkonsistens mellem Wt, T og d.\n');
    allChecksOK = false;
end

if all(calculation.dynamicFactorKv >= 1-1e-12)
    fprintf('OK - alle dynamiske faktorer Kv er mindst 1.\n');
else
    fprintf('IKKE OK - mindst én dynamisk faktor er under 1.\n');
    allChecksOK = false;
end

results.allAutomaticChecksOK = allChecksOK;

%% PLOTS
if makeWidthSweepPlot
    allRequiredWidths = [ ...
        calculation.requiredWidthDriveMM; ...
        calculation.requiredWidthDrivenMM];

    [~,criticalLinearIndex] = max(allRequiredWidths(:));

    [criticalRoleRow,criticalStage] = ...
        ind2sub(size(allRequiredWidths),criticalLinearIndex);

    if criticalRoleRow == 1
        criticalRoleText = "drivende";
        criticalY = calculation.lewisFactorDrive(criticalStage);
        criticalAllowableMPa = ...
            allowableStressDriveMPa(criticalStage);
    else
        criticalRoleText = "drevet";
        criticalY = calculation.lewisFactorDriven(criticalStage);
        criticalAllowableMPa = ...
            allowableStressDrivenMPa(criticalStage);
    end

    criticalRequiredWidthMM = ...
        allRequiredWidths(criticalRoleRow,criticalStage);

    widthSweepMM = linspace( ...
        max(0.25*criticalRequiredWidthMM,0.1), ...
        2.0*criticalRequiredWidthMM, ...
        250);

    stressSweepMPa = ...
        calculation.dynamicFactorKv(criticalStage) * ...
        calculation.tangentialForceN(criticalStage) ./ ...
        (widthSweepMM * moduleStageMM(criticalStage) * criticalY);

    figure('Name','T3 - tandbredde og tandfodsspaending');

    plot(widthSweepMM,stressSweepMPa,'LineWidth',1.2);
    hold on
    yline(criticalAllowableMPa,'--','Tilladt spaending');
    xline(criticalRequiredWidthMM,'--','Kraevet bredde');

    if ~isnan(faceWidthStageMM(criticalStage))
        actualStressMPa = ...
            calculation.dynamicFactorKv(criticalStage) * ...
            calculation.tangentialForceN(criticalStage) / ...
            (faceWidthStageMM(criticalStage) * ...
             moduleStageMM(criticalStage) * criticalY);

        plot(faceWidthStageMM(criticalStage),actualStressMPa,'o', ...
            'MarkerSize',7,'LineWidth',1.2);
    end

    hold off
    grid on

    xlabel('Tandbredde b [mm]');
    ylabel('Dynamisk tandfodsspaending [MPa]');

    title(sprintf( ...
        'Kritisk hjul: trin %d, %s', ...
        criticalStage,char(criticalRoleText)));

    legend('Beregnet spaending','Location','best');
end

%% PHYSICAL CONCLUSION
[globalRequiredWidthMM,globalCriticalIndex] = max(gearRequiredWidthMM);
globalCriticalStage = gearStage(globalCriticalIndex);
globalCriticalRole = gearRole(globalCriticalIndex);

fprintf('\nFYSISK KONKLUSION:\n');
fprintf(['Det stoerste kontinuerlige breddekrav er %.3f mm og ', ...
    'kommer fra trin %d, %s hjul.\n'], ...
    globalRequiredWidthMM,globalCriticalStage,char(globalCriticalRole));

if all(isnan(faceWidthStageMM))
    fprintf(['Der er ikke angivet faktiske tandbredder. Vaelg en ', ...
        'praktisk eller standardiseret bredde, som mindst svarer ', ...
        'til kravene, og gentag kontrollen.\n']);
elseif calculation.allProvidedWidthsOK
    fprintf(['OK: Alle angivne tandbredder opfylder de tilladelige ', ...
        'tandfodsspaendinger efter kursusmetoden.\n']);
else
    fprintf(['IKKE OK: Mindst én angivet tandbredde er for lille ', ...
        'i forhold til den tilladelige tandfodsspaending.\n']);
end

fprintf(['Resultatet afhaenger direkte af Wt, Qv, mc og den ', ...
    'tilladelige spaending. Disse vaerdier skal kunne begrundes ', ...
    'ud fra T1, T2, opgaven og materialedata.\n']);

%% OPTIONAL TEST CASES
if runCourseRegressionTests
    testName = strings(4,1);
    testPassed = false(4,1);
    testDetail = strings(4,1);

    % Test 1: Eksempeleksamen, problem 1.
    examCase = calculateT3SpurGear( ...
        20,40,2,20,5, ...
        "torque",40,NaN, ...
        "rpm",3000,NaN, ...
        "calculate",NaN, ...
        100,100,NaN,[],1.20);

    testName(1) = "Eksempeleksamen: noedvendig tandbredde";

    testPassed(1) = ...
        abs(examCase.contactRatioUsed - 1.635185963571) < 1e-10 && ...
        abs(examCase.tangentialForceN - 2000) < 1e-10 && ...
        abs(examCase.pitchLineVelocityMPerSec - ...
            6.283185307180) < 1e-10 && ...
        abs(examCase.dynamicFactorKv - 1.578681736145) < 1e-10 && ...
        abs(examCase.requiredStageWidthMM - ...
            28.412249965961) < 1e-9;

    testDetail(1) = sprintf([ ...
        'mc=%.4f, Wt=%.0f N, Kv=%.3f, b=%.3f mm'], ...
        examCase.contactRatioUsed, ...
        examCase.tangentialForceN, ...
        examCase.dynamicFactorKv, ...
        examCase.requiredStageWidthMM);

    % Test 2: Kursusopgavens to geartrin med publicerede, afrundede input.
    courseCase = calculateT3SpurGear( ...
        [17,17],[100,74],[2,3],[20,20],[5,5], ...
        "force",[NaN,NaN],[674,10600], ...
        "velocity",[NaN,NaN],[5.2,1.33], ...
        "manual",[1.684,1.665], ...
        [100,100],[100,100],[5*pi*2,5*pi*3],[],1.20);

    expectedCourseStressMPa = [ ...
        30.360058071, ...
        21.428431237, ...
        178.364310733, ...
        126.648446659];

    actualCourseStressMPa = [ ...
        courseCase.stressDriveMPa(1), ...
        courseCase.stressDrivenMPa(1), ...
        courseCase.stressDriveMPa(2), ...
        courseCase.stressDrivenMPa(2)];

    testName(2) = "Kursusopgave: fire tandfodsspaendinger";

    testPassed(2) = ...
        max(abs(actualCourseStressMPa - ...
        expectedCourseStressMPa)) < 1e-8;

    testDetail(2) = sprintf([ ...
        'sigma=[%.1f, %.1f, %.0f, %.0f] MPa'], ...
        actualCourseStressMPa);

    % Test 3: Qv=12 skal give B=0 og Kv=1.
    qualityLimitCase = calculateT3SpurGear( ...
        20,40,2,20,12, ...
        "force",NaN,2000, ...
        "velocity",NaN,100, ...
        "calculate",NaN, ...
        100,100,30,[],1.20);

    testName(3) = "Randtilfaelde: Qv=12 giver Kv=1";

    testPassed(3) = ...
        abs(qualityLimitCase.dynamicParameterB) < 1e-12 && ...
        abs(qualityLimitCase.dynamicFactorKv - 1) < 1e-12;

    testDetail(3) = sprintf( ...
        'B=%.3g, Kv=%.6f', ...
        qualityLimitCase.dynamicParameterB, ...
        qualityLimitCase.dynamicFactorKv);

    % Test 4: 28 mm er mindre end eksamenskravet 28.412 mm.
    failureCase = calculateT3SpurGear( ...
        20,40,2,20,5, ...
        "torque",40,NaN, ...
        "rpm",3000,NaN, ...
        "calculate",NaN, ...
        100,100,28,[],1.20);

    testName(4) = "Fejltilfaelde: b=28 mm er for lille";

    testPassed(4) = ...
        ~failureCase.stageWidthOK && ...
        failureCase.stressDriveMPa > 100 && ...
        ~failureCase.allProvidedWidthsOK;

    testDetail(4) = sprintf([ ...
        'sigma_pinion=%.2f MPa, status=%s'], ...
        failureCase.stressDriveMPa, ...
        char(failureCase.stageStatus));

    testTable = table( ...
        testName,testPassed,testDetail, ...
        'VariableNames',{'Test','Passed','Detail'});

    disp('Indbyggede regressionstests:')
    disp(testTable)

    results.courseTests = testTable;

    if all(testPassed)
        fprintf('OK - alle fire indbyggede tests bestod.\n');
    else
        error('T3:RegressionTestFailed', ...
            'Mindst én indbygget regressionstest fejlede.');
    end
end

%% LOCAL FUNCTIONS
function out = calculateT3SpurGear( ...
    zDrive, ...
    zDriven, ...
    moduleStageMM, ...
    pressureAngleDeg, ...
    qualityNumberQv, ...
    loadInputMode, ...
    driveTorqueNm, ...
    tangentialForceNInput, ...
    speedInputMode, ...
    driveSpeedRPM, ...
    pitchLineVelocityInputMPerSec, ...
    contactRatioMode, ...
    manualContactRatio, ...
    allowableStressDriveMPa, ...
    allowableStressDrivenMPa, ...
    faceWidthStageMM, ...
    availableStandardFaceWidthsMM, ...
    minimumContactRatio)

    zDrive = zDrive(:).';
    zDriven = zDriven(:).';
    moduleStageMM = moduleStageMM(:).';
    pressureAngleDeg = pressureAngleDeg(:).';
    qualityNumberQv = qualityNumberQv(:).';
    driveTorqueNm = driveTorqueNm(:).';
    tangentialForceNInput = tangentialForceNInput(:).';
    driveSpeedRPM = driveSpeedRPM(:).';
    pitchLineVelocityInputMPerSec = ...
        pitchLineVelocityInputMPerSec(:).';
    manualContactRatio = manualContactRatio(:).';
    allowableStressDriveMPa = allowableStressDriveMPa(:).';
    allowableStressDrivenMPa = allowableStressDrivenMPa(:).';
    faceWidthStageMM = faceWidthStageMM(:).';
    availableStandardFaceWidthsMM = ...
        sort(unique(availableStandardFaceWidthsMM(:).'));

    numberOfStages = numel(zDrive);

    drivePitchDiameterMM = ...
        zDrive .* moduleStageMM;

    drivenPitchDiameterMM = ...
        zDriven .* moduleStageMM;

    stageRatio = ...
        zDriven ./ zDrive;

    driveAddendumDiameterMM = ...
        drivePitchDiameterMM + 2*moduleStageMM;

    drivenAddendumDiameterMM = ...
        drivenPitchDiameterMM + 2*moduleStageMM;

    driveBaseDiameterMM = ...
        drivePitchDiameterMM .* cosd(pressureAngleDeg);

    drivenBaseDiameterMM = ...
        drivenPitchDiameterMM .* cosd(pressureAngleDeg);

    centerDistanceMM = 0.5*( ...
        drivePitchDiameterMM + drivenPitchDiameterMM);

    driveRadicand = ...
        driveAddendumDiameterMM.^2 - driveBaseDiameterMM.^2;

    drivenRadicand = ...
        drivenAddendumDiameterMM.^2 - drivenBaseDiameterMM.^2;

    if any(driveRadicand < -1e-10) || ...
       any(drivenRadicand < -1e-10)
        error('T3:ImpossibleGeometry', ...
            'Tandtopcirklen ligger inden for grundcirklen.');
    end

    driveRadicand = max(driveRadicand,0);
    drivenRadicand = max(drivenRadicand,0);

    pathOfContactMM = 0.5*( ...
        sqrt(driveRadicand) + sqrt(drivenRadicand)) - ...
        centerDistanceMM .* sind(pressureAngleDeg);

    basePitchMM = ...
        pi*moduleStageMM.*cosd(pressureAngleDeg);

    contactRatioCalculated = ...
        pathOfContactMM ./ basePitchMM;

    if strcmpi(contactRatioMode,"calculate")
        contactRatioUsed = contactRatioCalculated;
        contactRatioSource = ...
            repmat("Beregnet standardgeometri",numberOfStages,1);
    else
        contactRatioUsed = manualContactRatio;
        contactRatioSource = ...
            repmat("Manuelt input",numberOfStages,1);
    end

    contactFactorKe = ...
        1 ./ contactRatioUsed;

    if strcmpi(loadInputMode,"torque")
        tangentialForceN = ...
            2*driveTorqueNm*1000 ./ drivePitchDiameterMM;

        equivalentDriveTorqueNm = ...
            driveTorqueNm;
    else
        tangentialForceN = ...
            tangentialForceNInput;

        equivalentDriveTorqueNm = ...
            tangentialForceN .* drivePitchDiameterMM / 2000;
    end

    if strcmpi(speedInputMode,"rpm")
        driveOmegaRadPerSec = ...
            driveSpeedRPM*2*pi/60;

        pitchLineVelocityMPerSec = ...
            drivePitchDiameterMM/2000 .* driveOmegaRadPerSec;
    else
        pitchLineVelocityMPerSec = ...
            pitchLineVelocityInputMPerSec;

        driveOmegaRadPerSec = ...
            2*pitchLineVelocityMPerSec ./ ...
            (drivePitchDiameterMM/1000);

        driveSpeedRPM = ...
            driveOmegaRadPerSec*60/(2*pi);
    end

    dynamicParameterB = ...
        0.25*(12-qualityNumberQv).^(2/3);

    dynamicParameterA = ...
        50 + 56*(1-dynamicParameterB);

    dynamicFactorKv = ( ...
        (dynamicParameterA + ...
         sqrt(200*pitchLineVelocityMPerSec)) ./ ...
        dynamicParameterA).^dynamicParameterB;

    formFactorDrive = ...
        2.2 + 3.1*exp(-zDrive/14);

    formFactorDriven = ...
        2.2 + 3.1*exp(-zDriven/14);

    lewisFactorDrive = ...
        1 ./ (contactFactorKe .* formFactorDrive);

    lewisFactorDriven = ...
        1 ./ (contactFactorKe .* formFactorDriven);

    requiredWidthDriveMM = ...
        dynamicFactorKv .* tangentialForceN ./ ...
        (allowableStressDriveMPa .* ...
         moduleStageMM .* lewisFactorDrive);

    requiredWidthDrivenMM = ...
        dynamicFactorKv .* tangentialForceN ./ ...
        (allowableStressDrivenMPa .* ...
         moduleStageMM .* lewisFactorDriven);

    requiredStageWidthMM = max( ...
        [requiredWidthDriveMM;requiredWidthDrivenMM],[],1);

    criticalRole = repmat("Drivende",numberOfStages,1);
    drivenCritical = ...
        requiredWidthDrivenMM > requiredWidthDriveMM;
    criticalRole(drivenCritical(:)) = "Drevet";

    stressDriveMPa = ...
        NaN(1,numberOfStages);

    stressDrivenMPa = ...
        NaN(1,numberOfStages);

    safetyFactorDrive = ...
        NaN(1,numberOfStages);

    safetyFactorDriven = ...
        NaN(1,numberOfStages);

    widthProvided = ...
        isfinite(faceWidthStageMM);

    stressDriveMPa(widthProvided) = ...
        dynamicFactorKv(widthProvided) .* ...
        tangentialForceN(widthProvided) ./ ...
        (faceWidthStageMM(widthProvided) .* ...
         moduleStageMM(widthProvided) .* ...
         lewisFactorDrive(widthProvided));

    stressDrivenMPa(widthProvided) = ...
        dynamicFactorKv(widthProvided) .* ...
        tangentialForceN(widthProvided) ./ ...
        (faceWidthStageMM(widthProvided) .* ...
         moduleStageMM(widthProvided) .* ...
         lewisFactorDriven(widthProvided));

    safetyFactorDrive(widthProvided) = ...
        allowableStressDriveMPa(widthProvided) ./ ...
        stressDriveMPa(widthProvided);

    safetyFactorDriven(widthProvided) = ...
        allowableStressDrivenMPa(widthProvided) ./ ...
        stressDrivenMPa(widthProvided);

    stageWidthOK = ...
        false(1,numberOfStages);

    stageWidthOK(widthProvided) = ...
        faceWidthStageMM(widthProvided) >= ...
        requiredStageWidthMM(widthProvided)*(1-1e-12);

    selectedStandardWidthMM = ...
        NaN(1,numberOfStages);

    if ~isempty(availableStandardFaceWidthsMM)
        for k = 1:numberOfStages
            firstAdequateIndex = find( ...
                availableStandardFaceWidthsMM >= ...
                requiredStageWidthMM(k),1,'first');

            if ~isempty(firstAdequateIndex)
                selectedStandardWidthMM(k) = ...
                    availableStandardFaceWidthsMM(firstAdequateIndex);
            end
        end
    end

    gearStatusDrive = ...
        repmat("DIMENSIONER",numberOfStages,1);

    gearStatusDriven = ...
        repmat("DIMENSIONER",numberOfStages,1);

    gearStatusDrive(widthProvided(:) & ...
        stressDriveMPa(:) <= allowableStressDriveMPa(:)*(1+1e-12)) = ...
        "OK";

    gearStatusDrive(widthProvided(:) & ...
        stressDriveMPa(:) > allowableStressDriveMPa(:)*(1+1e-12)) = ...
        "IKKE OK";

    gearStatusDriven(widthProvided(:) & ...
        stressDrivenMPa(:) <= allowableStressDrivenMPa(:)*(1+1e-12)) = ...
        "OK";

    gearStatusDriven(widthProvided(:) & ...
        stressDrivenMPa(:) > allowableStressDrivenMPa(:)*(1+1e-12)) = ...
        "IKKE OK";

    stageStatus = ...
        repmat("DIMENSIONER",numberOfStages,1);

    stageStatus(widthProvided(:) & stageWidthOK(:)) = ...
        "OK";

    stageStatus(widthProvided(:) & ~stageWidthOK(:)) = ...
        "IKKE OK";

    allProvidedWidthsOK = ...
        all(stageWidthOK(widthProvided));

    if ~any(widthProvided)
        allProvidedWidthsOK = false;
    end

    out = struct;
    out.drivePitchDiameterMM = drivePitchDiameterMM;
    out.drivenPitchDiameterMM = drivenPitchDiameterMM;
    out.stageRatio = stageRatio;
    out.driveAddendumDiameterMM = driveAddendumDiameterMM;
    out.drivenAddendumDiameterMM = drivenAddendumDiameterMM;
    out.driveBaseDiameterMM = driveBaseDiameterMM;
    out.drivenBaseDiameterMM = drivenBaseDiameterMM;
    out.centerDistanceMM = centerDistanceMM;
    out.pathOfContactMM = pathOfContactMM;
    out.basePitchMM = basePitchMM;
    out.contactRatioCalculated = contactRatioCalculated;
    out.contactRatioUsed = contactRatioUsed;
    out.contactRatioSource = contactRatioSource;
    out.contactFactorKe = contactFactorKe;
    out.tangentialForceN = tangentialForceN;
    out.equivalentDriveTorqueNm = equivalentDriveTorqueNm;
    out.driveSpeedRPM = driveSpeedRPM;
    out.driveOmegaRadPerSec = driveOmegaRadPerSec;
    out.pitchLineVelocityMPerSec = pitchLineVelocityMPerSec;
    out.dynamicParameterA = dynamicParameterA;
    out.dynamicParameterB = dynamicParameterB;
    out.dynamicFactorKv = dynamicFactorKv;
    out.formFactorDrive = formFactorDrive;
    out.formFactorDriven = formFactorDriven;
    out.lewisFactorDrive = lewisFactorDrive;
    out.lewisFactorDriven = lewisFactorDriven;
    out.requiredWidthDriveMM = requiredWidthDriveMM;
    out.requiredWidthDrivenMM = requiredWidthDrivenMM;
    out.requiredStageWidthMM = requiredStageWidthMM;
    out.criticalRole = criticalRole;
    out.stressDriveMPa = stressDriveMPa;
    out.stressDrivenMPa = stressDrivenMPa;
    out.safetyFactorDrive = safetyFactorDrive;
    out.safetyFactorDriven = safetyFactorDriven;
    out.stageWidthOK = stageWidthOK;
    out.selectedStandardWidthMM = selectedStandardWidthMM;
    out.gearStatusDrive = gearStatusDrive;
    out.gearStatusDriven = gearStatusDriven;
    out.stageStatus = stageStatus;
    out.allProvidedWidthsOK = allProvidedWidthsOK;
    out.allContactRatiosOK = ...
        all(contactRatioUsed >= minimumContactRatio);
end
